
services:
  cassandra:
    image: cassandra:4.1
    networks:
      - render-network

  render:
    build:
      context: .
      dockerfile: Dockerfile
      target: testing
      args:
        APPNAME: render
        CASSANDRA_ADDRS: "['cassandra']"
    ports:
      - "8080:80"
    networks:
      - render-network
    depends_on:
      - cassandra
  
networks:
  render-network:
    driver: bridge
