
# Validate the Renderer Metadata model
name: Validate Model

on:
    push:
        branches: main
    pull_request:
        branches: main
    workflow_dispatch:

permissions: read-all

concurrency:
    group: '${{ github.workflow }}-${{ github.ref }}'
    cancel-in-progress: true

jobs:
    validate-docker-compose:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Docker repository
              run: |
                apt update
                apt install ca-certificates curl
                install -m 0755 -d /etc/apt/keyrings
                curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
                chmod a+r /etc/apt/keyrings/docker.asc
                echo \
                    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
                    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
                    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
                sudo apt-get update
            
            - name: Install Docker packages
              run: |
                apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            
            - name: Verify Docker Engine installation
              run: |
                docker run hello-world

            - uses: actions/checkout@v4
            - run: |
                docker-compose build

